export const themes = {
  heaven: {
    name: 'Heaven',
    bg: 'bg-gradient-to-br from-amber-50 via-rose-50 to-sky-100',
    card: 'bg-white/70 backdrop-blur-xl border border-white/50',
    cardHover: 'hover:bg-white/90 hover:shadow-xl hover:shadow-rose-200/30',
    primary: 'bg-gradient-to-r from-rose-400 to-amber-400',
    primaryText: 'text-rose-600',
    accent: 'text-amber-600',
    button: 'bg-gradient-to-r from-rose-400 to-amber-400 hover:from-rose-500 hover:to-amber-500 text-white shadow-lg shadow-rose-300/50',
    buttonSecondary: 'bg-white/50 hover:bg-white/80 text-rose-600 border border-rose-200',
    input: 'bg-white/60 border-rose-200 focus:border-rose-400 focus:ring-rose-300',
    tag: 'bg-rose-100 text-rose-700 border border-rose-200',
    tagSelected: 'bg-gradient-to-r from-rose-400 to-amber-400 text-white border-transparent',
    online: 'bg-emerald-400',
    text: 'text-slate-800',
    textMuted: 'text-slate-500',
    glow: 'shadow-2xl shadow-amber-200/50',
    icon: '👼',
    font: "'Cormorant Garamond', serif",
  },
  hell: {
    name: 'Hell',
    bg: 'bg-gradient-to-br from-black via-red-950 to-black',
    card: 'bg-black/60 backdrop-blur-xl border border-red-900/50',
    cardHover: 'hover:bg-red-950/40 hover:shadow-xl hover:shadow-red-900/30',
    primary: 'bg-gradient-to-r from-red-600 to-orange-600',
    primaryText: 'text-red-500',
    accent: 'text-orange-500',
    button: 'bg-gradient-to-r from-red-600 to-orange-600 hover:from-red-500 hover:to-orange-500 text-white shadow-lg shadow-red-900/50',
    buttonSecondary: 'bg-red-950/50 hover:bg-red-900/50 text-red-400 border border-red-800',
    input: 'bg-black/60 border-red-900 focus:border-red-500 focus:ring-red-800 text-white placeholder-red-300/50',
    tag: 'bg-red-950 text-red-400 border border-red-800',
    tagSelected: 'bg-gradient-to-r from-red-600 to-orange-600 text-white border-transparent',
    online: 'bg-orange-500',
    text: 'text-white',
    textMuted: 'text-red-300/70',
    glow: 'shadow-2xl shadow-red-900/50',
    icon: '😈',
    font: "'Bebas Neue', sans-serif",
  }
};
